
The following have been reloaded with a version change:
  1) FFTW/3.3.8-gompic-2019b => FFTW/3.3.8-gompi-2019b
  2) OpenMPI/3.1.4-gcccuda-2019b => OpenMPI/3.1.4-GCC-8.3.0
  3) ScaLAPACK/2.0.2-gompic-2019b => ScaLAPACK/2.0.2-gompi-2019b
  4) SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4 => SciPy-bundle/2019.10-foss-2019b-Python-3.7.4


The following have been reloaded with a version change:
  1) SciPy-bundle/2019.10-foss-2019b-Python-3.7.4 => SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4

--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[48630,1],0] (PID 7022)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
2020-05-31 16:48:42.972445: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1

START MCDO
shape preditctions:  (250, 8750, 10)
0/250
1/250
2/250
3/250
4/250
5/250
6/250
7/250
8/250
9/250
10/250
11/250
12/250
13/250
14/250
15/250
16/250
17/250
18/250
19/250
20/250
21/250
22/250
23/250
24/250
25/250
26/250
27/250
28/250
29/250
30/250
31/250
32/250
33/250
34/250
35/250
36/250
37/250
38/250
39/250
40/250
41/250
42/250
43/250
44/250
45/250
46/250
47/250
48/250
49/250
50/250
51/250
52/250
53/250
54/250
55/250
56/250
57/250
58/250
59/250
60/250
61/250
62/250
63/250
64/250
65/250
66/250
67/250
68/250
69/250
70/250
71/250
72/250
73/250
74/250
75/250
76/250
77/250
78/250
79/250
80/250
81/250
82/250
83/250
84/250
85/250
86/250
87/250
88/250
89/250
90/250
91/250
92/250
93/250
94/250
95/250
96/250
97/250
98/250
99/250
100/250
101/250
102/250
103/250
104/250
105/250
106/250
107/250
108/250
109/250
110/250
111/250
112/250
113/250
114/250
115/250
116/250
117/250
118/250
119/250
120/250
121/250
122/250
123/250
124/250
125/250
126/250
127/250
128/250
129/250
130/250
131/250
132/250
133/250
134/250
135/250
136/250
137/250
138/250
139/250
140/250
141/250
142/250
143/250
144/250
145/250
146/250
147/250
148/250
149/250
150/250
151/250
152/250
153/250
154/250
155/250
156/250
157/250
158/250
159/250
160/250
161/250
162/250
163/250
164/250
165/250
166/250
167/250
168/250
169/250
170/250
171/250
172/250
173/250
174/250
175/250
176/250
177/250
178/250
179/250
180/250
181/250
182/250
183/250
184/250
185/250
186/250
187/250
188/250
189/250
190/250
191/250
192/250
193/250
194/250
195/250
196/250
197/250
198/250
199/250
200/250
201/250
202/250
203/250
204/250
205/250
206/250
207/250
208/250
209/250
210/250
211/250
212/250
213/250
214/250
215/250
216/250
217/250
218/250
219/250
220/250
221/250
222/250
223/250
224/250
225/250
226/250
227/250
228/250
229/250
230/250
231/250
232/250
233/250
234/250
235/250
236/250
237/250
238/250
239/250
240/250
241/250
242/250
243/250
244/250
245/250
246/250
247/250
248/250
249/250
Correct: 7492, wrong: 1258, accuracy: 85.62285714285714%

Mean probability on true label of CIFAR10 test dataset when correctly predicted = 98.65%
Process Process-1:
Traceback (most recent call last):
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "use_Arrays.py", line 49, in with_profiling
    ret = fn(*args, **kwargs)
  File "use_Arrays.py", line 857, in MCDO
    method_main()
  File "use_Arrays.py", line 844, in method_main
    test_on_own_funcV2(METHODNAME, mcdo_own_predictions, y_test)
  File "use_Arrays.py", line 540, in test_on_own_funcV2
    print("Mean uncertainty on true label of {} test dataset when correctly predicted = {:.2%}".format(DATANAME, mean(correct_unc)))
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/statistics.py", line 311, in mean
    T, total, count = _sum(data)
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/statistics.py", line 147, in _sum
    for n,d in map(_exact_ratio, values):
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/statistics.py", line 229, in _exact_ratio
    raise TypeError(msg.format(type(x).__name__))
TypeError: can't convert type 'ndarray' to numerator/denominator

START MCBN
slurmstepd: error: *** JOB 11842867 ON pg-gpu04 CANCELLED AT 2020-05-31T18:00:01 ***


###############################################################################
Peregrine Cluster
Job 11842867 for user 's2934833'
Finished at: Sun May 31 18:00:03 CEST 2020

Job details:
============

Name                : CombArrays
User                : s2934833
Partition           : gpu
Nodes               : pg-gpu04
Cores               : 12
State               : CANCELLED,CANCELLED by 0
Submit              : 2020-05-31T16:48:04
Start               : 2020-05-31T16:48:38
End                 : 2020-05-31T18:00:03
Reserved walltime   : 04:00:00
Used walltime       : 01:11:25
Used CPU time       : 01:10:51 (efficiency:  8.27%)
% User (Computation): 99.88%
% System (I/O)      :  0.11%
Mem reserved        : 8000M/node
Max Mem used        : 2.91G (pg-gpu04)
Max Disk Write      : 194.56K (pg-gpu04)
Max Disk Read       : 7.13M (pg-gpu04)
Average GPU usage   : 0.0% (pg-gpu04)


Acknowledgements:
=================

Please see this page for information about acknowledging Peregrine in your publications:

https://wiki.hpc.rug.nl/peregrine/additional_information/scientific_output

################################################################################
